### PR TITLE
Add patch for GitHub actions

### PR DESCRIPTION
**Pull request by waybackarchiver**
Hello there,

The [tor-actions](/tor-actions) project uses GitHub Actions to automatically build Tor binaries, but the build scripts are not yet available in GitHub Actions for the Darwin environment. It appears that the number of cores condition is invalid, so it has been changed below.

```diff
-  if  echo "$1" | grep -Eq "$re" ; then
+  if ! echo "$1" | grep -Eq "$re" ; then
```

Furthermore, the [tor-versions](/tor-actions/versions) needs the full file and removes the `trap cleanup EXIT` from `build_linux.sh` and `build_mingw.sh`.

See the [builder workflow](https://github.com/tor-actions/versions/blob/c16b618b2926600d483bcfd9eee70ae8b1413f5c/.github/workflows/builder.yml#L93-L96) for more details.

### CODE REVIEW

**Comment by fmarier** [comment]
I merged the invalid condition fix into https://github.com/brave/tor_build_scripts/pull/85, but I'm not sure what the other one does.

I'm not familiar with what this `trap cleanup EXIT` does (our git history is not super helpful) or why it's a problem in your environment.

**Comment by waybackarchiver** [comment]
@fmarier Thanks you for your response!

Removing the `trap cleanup EXIT` prevents its cleaning the compiled files, lets them to be exported from inside image.

**Comment by fmarier** [comment]
I can't find a lot of information as to why we added this image cleaning code in https://github.com/brave/tor_build_scripts/commit/f85674db537d898b6e222c953e5daab807eff1b4, but according to [this comment](https://github.com/brave/tor_build_scripts/pull/72#pullrequestreview-762120533), it seems like it was related to our Jenkins setup and that without it the disks will fill up. Maybe @wknapik remembers?

**Comment by wknapik** [comment]
@fmarier the trap on EXIT is a great way to clean up in shell scripts. That said, this particular cleanup does two things - `docker rm -f tor-brave`, which should not be needed, since `docker run --name tor-brave` is called with `--rm`; and `docker rmi tor-brave`, which deletes the whole image and also shouldn't be super relevant, since we always use the same image name, so disk consumption should not grow over time. `cleanup` is also called at the beginning of a build, so whether the trap stays, or goes, should not have a big impact.

**Comment by waybackarchiver** [comment]
> 

Yes. It would be ideal if you could remove the clear binary section of the script.

**Comment by fmarier** [comment]
@waybackarchiver Please take a look at https://github.com/brave/tor_build_scripts/pull/90 where I'm applied the rest of your patch.

**Pull request closed without merging**
